options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'us-central1-docker.pkg.dev/polished-core-463907-m5/sonar/sonar:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧪 Running Maven build..."
        mvn clean install

        echo "✅ Build complete!"
